# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 561, 391))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Справка"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">     </span><span style=\" font-size:12pt; font-weight:600;\">Описание</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Приложение предназначено для вычисления определенного интеграла (нахождение площади фигуры, ограниченной какой-либо функцией сверху на указанном промежутке методом прямоугольников). </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">2.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt;\">     </span><span style=\" font-size:12pt; font-weight:600;\">Начало работы</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Для начала работы с программой необходимо кликнуть по кнопке «Вычислить площадь», после чего у вас откроется окно, на котором вы уже можете начать работать.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#333333;\">3.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; font-weight:600; color:#333333; background-color:#ffffff;\">Описание параметров</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Для вычисления площади вам потребуется ввести функцию согласно правилам языка Python (все возможные операции будут представлены ниже), параметры a и b, отвечающие за границы фигуры по координате </span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">абсцисс – Х (икс), a, соответственно, левая граница, b – правая, и параметр n, отвечающий за количество прямоугольников, на которое будет разбита фигура для вычисления площади (чем больше прямоугольников, тем выше точность вычисления). После введения всех параметров нажмите на кнопку «Вычислить» и в низу окна вы увидите результат. Если у вас возникла ошибка, еще раз ознакомьтесь со справкой, кликнув на пункт «Меню» на панели инструментов в левом верхнем углу окна и нажав кликнув на справку, в частности, с правилом записи функции.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#333333;\">4.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; font-weight:600; color:#333333; background-color:#ffffff;\">Загрузить данные из файла</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">Если у вас имеется файл с входными данными, кликните на пункт «Файл» на панели инструментов, выберите пункт «Открыть», в открывшимся проводнике выберите необходимый файл и нажмите на кнопку «Открыть». После чего можете вычислить результат. Данные в файле должны быть записаны в следующем формате:&lt;функция&gt;пробел&lt;левая_граница&gt;пробел&lt;правая_граница&gt;пробел&lt;левая граница&gt;пробел&lt;количество прямоугольников&gt;. Например: sqrt(x) 2 4 50.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333;\">5.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; font-weight:600; color:#333333; background-color:#ffffff;\">Возможные операции для записи функции</span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333;\">a.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">x**&lt;степень&gt;, пример x**3 (икс в кубе).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333;\">b.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">sqrt(x): корень из икса).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">c.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">      </span><span style=\" font-size:12pt; color:#333333;\">sin(x) (синус &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">d.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333;\">cos(x) (косинус &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">e.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333;\">tan(x) (тангенс &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">f.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">       </span><span style=\" font-size:12pt; color:#333333;\">asin(x) (арксинус &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">g.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333;\">acos(x) (арккосинус &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#fbfbfb;\"><span style=\" font-size:12pt; color:#333333;\">h.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; color:#333333;\">atan(x) (арктангенс &quot;x&quot;).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333;\">i.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">       </span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">log(&lt;основание&gt;,x) (логарифм x по указанному основанию).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333;\">j.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">       </span><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">exp(x) (экспонента).</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#333333;\">6.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; font-weight:600; color:#333333; background-color:#ffffff;\">Сохранение результата в файл</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">Введя данные и вычислив результат, вы можете его сохранить в файл, для этого кликните на пункт «Файл» на панели инструментов, выберите пункт «Сохранить», выберите место для сохранения в открывшимся проводнике и нажмите на кнопку «Сохранить».</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#333333;\">7.</span><span style=\" font-family:\'Times New Roman\'; font-size:7pt; color:#333333;\">     </span><span style=\" font-size:12pt; font-weight:600; color:#333333; background-color:#ffffff;\">Возврат в меню</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\">Что бы вернуть в главное меню, нажмите на пункт «Меню» на панели инструментов и выберите «Главное меню».</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#333333; background-color:#ffffff;\"> </span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"> </span><span style=\" font-size:8pt;\"> </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
